# ifndef _myerrors_H
  	#define myerrors_h
enum ERRORS{FALT_ARG=65,FALT_NOMB_ARCH=66,ARG_DESC_O_EXTRA=67,NO_ABRE_ARCH_L=68,NO_ABRE_ARCH_E=69,FALT_OPC_REQ=70,VAL_RANG_NO_PERM=71,ERR_EN_LA_CONV_RANGO=72, OP_REPEAT=73};
# endif

